### ISSUE TITLE
Should reverse proxy authenticate requests to Geoserver and NodeODM?

### ISSUE THREAD

**Issue by jreyesr** [IS-AgroSmart/AgroSmart-Top#5]
Currently, anybody can make any request to Geoserver from the outside world (by reading `domain.com/geoserver/some/path`) and read any map. This (may?) be undesirable, since a malicious actor could enumerate all workspaces and access all maps.
~Regarding NodeODM, the same issue exists:~
* ~User can enumerate all tasks by GET `/nodeodm/task/list`~
* ~User can send POST requests to any task, just by knowing the UUID (which he can determine by the previous bullet point)~

EDIT: NodeODM risks are still valid, but access to `/nodeodm/...` URLs is now proxied through Django. Therefore, mitigation is much easier: make sure to send auth headers from the frontend, and check them in the backend before sending the true request to NodeODM.

TODO: Determine if that is an acceptable risk. If not, we should lock down access to Geoserver URLs ~via Traefik's [ForwardAuth](https://doc.traefik.io/traefik/middlewares/forwardauth/) middleware~ through Geoserver's own security settings.

Geoserver:
- [x] ~Add ForwardAuth middleware to Geoserver router. This will require changing the base middleware on the router to Chain, and add the StripPrefix and ForwardAuth middlewares as children.~
- [x] ~Implement the authentication endpoint on Django. Tracked separately, on https://github.com/IS-AgroSmart/AgroSmart-Web/issues/115~
- [x] Change the Geoserver admin password to something secure
- [x] Refactor server (Django) code to store Geoserver (now secure) password as an envvar, change all backend requests to the Geoserver API to use the new, secure PW. Tracked separately, on https://github.com/IS-AgroSmart/AgroSmart-Web/issues/115
- [x] ~Somehow send authentication information on the Geoserver requests from frontend. Probably set a cookie so that all requests from OpenLayers have auth info.~
- [x] Add instructions on the wiki about the necessary Geoserver configurations

NodeODM: 
- [x] Verify that all frontend code sends the required auth information on all requests to NodeODM. Tracked separately, on https://github.com/IS-AgroSmart/AgroSmart-Web/issues/115
- [x] Add an authentication header on all calls to `/nodeodm/...`

**Comment by jreyesr** [comment]
Closed on https://github.com/IS-AgroSmart/AgroSmart-Top/commit/1d080671cccd80f7c55c587d9ea40a9442151b4d
